server:
  port: 2222

spring:
  application:
    name: test-huge-excel

  thymeleaf:
    cache: false
    prefix: classpath:/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

  zipkin:
    base-url: http://localhost:9411
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/huge_excel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiguiquan.springcloud.entities  #所有entity别名所在包